/*
 * Copyright 2023 FIWARE Foundation e.V. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.fiware.iam;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import java.security.MessageDigest;
import java.util.Base64;
import java.util.Objects;
import lombok.SneakyThrows;
import org.fiware.iam.repository.Claim;
import org.fiware.iam.repository.Credential;
import org.fiware.iam.til.model.ClaimVO;
import org.fiware.iam.til.model.CredentialsVO;
import org.fiware.iam.tir.v5.model.AttributeDetailsVO;
import org.fiware.iam.tir.v5.model.AttributeVO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Responsible for mapping entities to the TIR v5 API response models.
 *
 * <p>Handles Base64 encoding of credential bodies, SHA-256 hex-encoded hashing for attribute IDs,
 * and mapping of v5-specific fields ({@code issuerType}, {@code tao}, {@code rootTao}).
 *
 * @author <a href="https://github.com/wistefan">Stefan Wiedemann</a>
 **/
@Mapper(componentModel = "jsr330")
public interface TIRv5Mapper {

  Logger LOGGER = LoggerFactory.getLogger(TIRv5Mapper.class);
  ObjectWriter OBJECT_WRITER = new ObjectMapper().writer();

  /** SHA-256 algorithm name used for attribute ID computation. */
  String SHA256_ALGORITHM = "SHA-256";

  /** Number of hex characters per byte. */
  int HEX_CHARS_PER_BYTE = 2;

  /** Format string for converting a byte to a two-character hex string. */
  String HEX_FORMAT = "%02x";

  /**
   * Maps a {@link Credential} entity to a TIL {@link CredentialsVO} for JSON serialization.
   *
   * <p>This is auto-generated by MapStruct and used internally to produce the JSON payload that is
   * then Base64-encoded for the v5 attribute body.
   *
   * @param credential the credential entity
   * @return the TIL credentials value object
   */
  @Mapping(target = "validFor.from", source = "validFrom")
  @Mapping(target = "validFor.to", source = "validTo")
  CredentialsVO credentialToCredentialsVO(Credential credential);

  /**
   * Maps a {@link Claim} entity to a {@link ClaimVO}.
   *
   * <p>Handles the deserialization of stored claim values back to their original object
   * representations. Reuses {@link TILMapper#readToObject} for value parsing.
   *
   * @param claim the claim entity
   * @return the claim value object
   */
  default ClaimVO claimToClaimVO(Claim claim) {
    return new ClaimVO()
        .name(claim.getName())
        .path(claim.getPath())
        .allowedValues(
            claim.getClaimValues().stream()
                .map(TILMapper::readToObject)
                .filter(Objects::nonNull)
                .toList());
  }

  /**
   * Maps a {@link Credential} entity to a v5 {@link AttributeVO}.
   *
   * <p>Serializes the credential to JSON, Base64-encodes the body, computes a SHA-256 hex-encoded
   * hash, and maps the v5-specific fields ({@code issuerType}, {@code tao}, {@code rootTao}).
   *
   * @param credential the credential entity
   * @return the v5 attribute value object
   */
  default AttributeVO credentialToAttributeVO(Credential credential) {
    CredentialsVO credentialsVO = credentialToCredentialsVO(credential);
    AttributeVO attributeVO = new AttributeVO();
    try {
      byte[] body = OBJECT_WRITER.writeValueAsBytes(credentialsVO);
      attributeVO.setBody(Base64.getEncoder().encodeToString(body));
      attributeVO.setHash(bytesToHex(getSHA256(body)));
    } catch (JsonProcessingException e) {
      LOGGER.warn(
          "Was not able to process credential {}. Will not include full data.",
          credential.getId(),
          e);
    }
    attributeVO.setIssuerType(mapIssuerType(credential.getIssuerType()));
    attributeVO.setTao(credential.getTao());
    attributeVO.setRootTao(credential.getRootTao());
    return attributeVO;
  }

  /**
   * Computes the v5 attribute ID for a credential as a SHA-256 hex-encoded hash of the
   * Base64-encoded credential body.
   *
   * @param credential the credential entity
   * @return the hex-encoded SHA-256 hash, or an empty string if serialization fails
   */
  default String computeAttributeId(Credential credential) {
    CredentialsVO credentialsVO = credentialToCredentialsVO(credential);
    try {
      byte[] body = OBJECT_WRITER.writeValueAsBytes(credentialsVO);
      return bytesToHex(getSHA256(body));
    } catch (JsonProcessingException e) {
      LOGGER.warn("Was not able to compute attribute ID for credential {}.", credential.getId(), e);
      return "";
    }
  }

  /**
   * Maps a {@link Credential} entity to a v5 {@link AttributeDetailsVO}, wrapping the attribute
   * with the issuer's DID.
   *
   * @param did the issuer's DID
   * @param credential the credential entity
   * @return the attribute details value object
   */
  default AttributeDetailsVO credentialToAttributeDetailsVO(String did, Credential credential) {
    AttributeDetailsVO details = new AttributeDetailsVO();
    details.setDid(did);
    details.setAttribute(credentialToAttributeVO(credential));
    return details;
  }

  /**
   * Maps an issuer type string from the database to the v5 {@link AttributeVO.IssuerType} enum.
   *
   * <p>Returns {@link AttributeVO.IssuerType#UNDEFINED} for null or unrecognized values.
   *
   * @param issuerType the issuer type string, may be null
   * @return the corresponding enum value
   */
  default AttributeVO.IssuerType mapIssuerType(String issuerType) {
    if (issuerType == null) {
      return AttributeVO.IssuerType.UNDEFINED;
    }
    return AttributeVO.IssuerType.toOptional(issuerType).orElse(AttributeVO.IssuerType.UNDEFINED);
  }

  /**
   * Computes the SHA-256 hash of the given byte array.
   *
   * @param toHash the data to hash
   * @return the SHA-256 hash bytes
   */
  @SneakyThrows
  default byte[] getSHA256(byte[] toHash) {
    MessageDigest digest = MessageDigest.getInstance(SHA256_ALGORITHM);
    return digest.digest(toHash);
  }

  /**
   * Converts a byte array to a lowercase hexadecimal string.
   *
   * @param bytes the byte array to convert
   * @return the hex-encoded string
   */
  default String bytesToHex(byte[] bytes) {
    StringBuilder sb = new StringBuilder(bytes.length * HEX_CHARS_PER_BYTE);
    for (byte b : bytes) {
      sb.append(String.format(HEX_FORMAT, b));
    }
    return sb.toString();
  }
}
