openapi: 3.0.3
info:
  title: Trusted Issuers List
  description: Maintain a list of trusted issuers of verifiable credentials
  version: 4.0.0
tags:
  - name: verfication
  - name: issuer
paths:
  /issuer:
    post:
      tags:
        - issuer
      operationId: createTrustedIssuer
      summary: Create a trusted issuer and its capabilities
      description: create trusted issuer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustedIssuer'
      responses:
        '201':
          description: Successfully created the issuer.
  /issuer/{did}:
    delete:
      tags:
        - issuer
      parameters:
        - $ref: '#/components/parameters/Id'
      operationId: deleteIssuerById
      description: Delete a single issuer
      responses:
        '204':
          description: Successfully deleted
    put:
      tags:
        - issuer
      parameters:
        - $ref: '#/components/parameters/Id'
      description: Update a single issuer
      operationId: replaceIssuer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustedIssuer'
      responses:
        '204':
          description: Successfully updated the issuer.
components:
  parameters:
    Id:
      name: did
      in: path
      required: true
      schema:
        type: string
        example: did:elsi:happypets
  schemas:
    TimeRange:
      type: object
      properties:
        from:
          type: string
          format: date-time
          example: '2017-07-21T17:32:28Z'
        to:
          type: string
          format: date-time
          example: '2023-07-21T17:32:28Z'
    Capabilities:
      type: object
      properties:
        validFor:
          $ref: '#/components/schemas/TimeRange'
        credentialsType:
          type: string
          example: "CustomerCredential"
        claims:
          type: array
          items:
            $ref: '#/components/schemas/Claim'
    TrustedIssuer:
      type: object
      properties:
        did:
          type: string
          example: did:elsi:happypets
        capabilities:
          type: array
          items:
            $ref: '#/components/schemas/Capabilities'
    Claim:
      type: object
      properties:
        name:
          type: string
          example: roles
        allowedValues:
          type: array
          items:
            type: object
          example:
            - true
            - 12
            - "GOLD_CUSTOMER"
            - "STANDARD_CUSTOMER"
            - name: "Customer"
              provider: "p"